# Generated by Django 3.2.3 on 2021-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Other')], max_length=20, null=True)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('date_of_joining', models.DateField()),
            ],
        ),
    ]
